---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guacamole
bases:
    - ../../../apps/guacamole
resources:
    - resources/secret.yaml
patches:
    - patch: |-
        - op: replace
          path: /spec/rules/0/host
          value: rdp.k3s.phealy.com
        - op: replace
          path: /spec/rules/1/host
          value: ssh.k3s.phealy.com
        - op: replace
          path: /spec/tls/0/hosts/0
          value: rdp.k3s.phealy.com
        - op: replace
          path: /spec/tls/0/hosts/1
          value: ssh.k3s.phealy.com
      target:
          group: networking.k8s.io
          version: v1
          kind: Ingress
          name: guacamole-external
    - patch: |-
        - op: replace
          path: /spec/rules/0/host
          value: rdp.k3s.phealy.com
        - op: replace
          path: /spec/rules/1/host
          value: ssh.k3s.phealy.com
        - op: replace
          path: /spec/tls/0/hosts/0
          value: rdp.k3s.phealy.com
        - op: replace
          path: /spec/tls/0/hosts/1
          value: ssh.k3s.phealy.com
      target:
          group: networking.k8s.io
          version: v1
          kind: Ingress
          name: guacamole-internal
