---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guacamole
bases:
    - ../../../apps/guacamole
resources:
    - resources/pv.yaml
    - resources/secret.yaml
patches:
    - patch: |-
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: guacamole-db
          namespace: guacamole
        spec:
          volumeMode: Filesystem
          volumeName: pvc-817d35a1-3a1c-4145-b6db-38daf3a62172
    - patch: |-
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: guacamole-fonts
          namespace: guacamole
        spec:
          volumeMode: Filesystem
          volumeName: pvc-2f770203-bbca-444e-91cd-38168319fa35
    - patch: |-
        - op: replace
          path: /spec/rules/0/host
          value: rdp.k3s.phealy.com
        - op: replace
          path: /spec/rules/1/host
          value: ssh.k3s.phealy.com
        - op: replace
          path: /spec/tls/0/hosts/0
          value: rdp.k3s.phealy.com
        - op: replace
          path: /spec/tls/0/hosts/1
          value: ssh.k3s.phealy.com
      target:
          group: networking.k8s.io
          version: v1
          kind: Ingress
          name: guacamole
          namespace: guacamole
