---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
    - resources/rbac.yaml
    - resources/configmap.yaml
    - resources/kube-vip.yaml
    - resources/cloud-controller.yaml
