apiVersion: v1
data:
  config.cfg: |
    provider = "google"
    client_id = "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"
    email_domains = [
      "phealy.com"
    ]
    http_address = ":8080"
    redirect_url = "https://pool.k3s.phealy.com/oauth2/callback"
    reverse_proxy = true
    cookie_refresh = "1h"
    skip_provider_button = true
    #cookie_csrf_per_request = true
    #cookie_csrf_expire = 5m
    #show_debug_on_error = true
    upstreams = [
      "http://127.0.0.1:5150"
    ]
kind: ConfigMap
metadata:
  name: oauth2-proxy
  namespace: nodejs-poolcontroller
