---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nodejs-poolcontroller
resources:
    - namespace.yaml
    - pv.yaml
    - pvc.yaml
    - configmap.yaml
    - deployment.yaml
    - service.yaml
    - ingress.yaml
