---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant
bases:
    - ../../../apps/home-assistant
patchesJson6902:
    - patch: |-
        - op: replace
          path: /spec/rules/0/host
          value: home-assistant.k3s.phealy.com
        - op: replace
          path: /spec/tls/0/hosts/0
          value: home-assistant.k3s.phealy.com
      target:
          group: networking.k8s.io
          version: v1
          kind: Ingress
          name: home-assistant
