---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guacamole
resources:
    - namespace.yaml
    - pvc.yaml
    - deployment-postgres.yaml
    - deployment-guacd.yaml
    - deployment-guacamole.yaml
    - service-postgres.yaml
    - service-guacd.yaml
    - service-guacamole.yaml
    - ingress.yaml
    - configmap-server.yaml
