---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: ingress-controller-internal
spec:
    releaseName: internal
    chart:
        spec:
            chart: ingress-nginx
            sourceRef:
                name: ingress-nginx
                kind: HelmRepository
            version: '>=1.0.0'
    interval: 1h0m0s
    install:
        remediation:
            retries: 3
    values:
        controller:
            admissionWebhooks:
                objectSelector:
                    matchExpressions:
                      - key: ingress-class
                        operator: NotIn
                        values:
                        - nginx-external
            config:
                client-body-buffer-size: 16k
                large-client-header-buffers: 4 16k
                proxy-buffer-size: 16k
                ssl-protocols: "TLSv1.2"
            extraArgs:
                default-ssl-certificate: ingress-nginx-internal/wildcard-certificate
            ingressClassByName: false
            ingressClassResource:
                name: nginx
                default: true
                controllerValue: "k8s.io/ingress-nginx-internal"
            nodeSelector:
                kubernetes.io/os: linux
            replicaCount: 3
            service:
                type: LoadBalancer
                externalTrafficPolicy: Local
            watchIngressWithoutClass: true
        defaultBackend:
            enabled: true
            nodeSelector:
                kubernetes.io/os: linux
