---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: unifi
resources:
    - deployment.yaml
    - ingress-internal.yaml
    - namespace.yaml
    - service.yaml
    - pvc.yaml
