---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: unifi
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
    storageClassName: files
