---
apiVersion: v1
kind: ConfigMap
metadata:
    name: pihole-dnsmasq
    namespace: pihole
data:
    099-phealy.conf: |
        rev-server=10.0.0.0/16,10.0.22.1
        server=/phealy.com/10.0.22.1
        server=/pahealy.com/10.0.22.1
        address=/time.nuri.net/10.0.23.2
