---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx-external
resources:
    - namespace.yaml
    - repository.yaml
    - ingress-controller-external.yaml
    - wildcard-certificate.yaml
