---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
    - ../../../infrastructure/nfs-subdir-external-provisioner
patches:
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
            name: nfs-subdir-external-provisioner
            namespace: nfs-system
        spec:
            values:
                nfs:
                    server: 10.0.23.2
                    path: /volume1/k3s.phealy.com
