apiVersion: ENC[AES256_GCM,data:/Ck=,iv:vk2lYPjgQv3qjd/ECUOls4FGJ4SNm+D7VDE6huNvZ28=,tag:y5aZZ89F2r0iEtnbq6Jbvw==,type:str]
data:
    database: ENC[AES256_GCM,data:uOPxzDAuAAXK0P/b,iv:FgsW+6z0jNtjSXqrTZIIO2oYQGoCgwdf5Uv5uqAyz9I=,tag:pyzkpqnDT7Pic6ndp+aZAA==,type:str]
    user_login: ENC[AES256_GCM,data:qBpMlg24l2mlWYTI,iv:/4uhj6lvrNDQdFub9XgZXy/YUckYsNBux/cJJjTJv4g=,tag:zIPj5MG0+AcZcoVCQ1no6A==,type:str]
    user_password: ENC[AES256_GCM,data:Qfcxqy0TI3K5NS8cJG75IjIZ44tQOrd7IwynOg==,iv:ka15GDFOGG3nj/SdkvGWy7L84uf0U7+CesR0ZTU5XwI=,tag:Cg1utCcOJjegOm1Yh+yaLg==,type:str]
kind: ENC[AES256_GCM,data:3bkMhTbI,iv:bl0ZONlTTYjegFLKN74FNYxsKcd0LPdr81Da6e+MsPU=,tag:ZsLAlea4ygct2q4OQsQgqg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ENtZyXNZ2WJe,iv:jEnzDMR1rfwiN7WgBaUZRsUZtzr//Me++A1rYh+E8qs=,tag:NQop7CzufUFb+A9vPyEIgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-06T12:26:00Z"
    mac: ENC[AES256_GCM,data:/eSn1p2HWwZ9WDjSh2gLkGnWlyqc9gqM080K2uCLPPQNo/YbEAzcFjnrM0DuxgfBtOFdKC+++/nFj2oGuDJ7tASPKess+rb4EY3SsgpmeV4d1QJjcijhXKIxC5YU13J3RS5M6wLAR8mhhjRNW6csK1c997p4VKotnhRCSLsiBpA=,iv:KrtHX5fVtMH489TeJRuZz+M3bX+leRAFo56yVrmh5Kg=,tag:vEE1Lcc56EI44yXoYetqIg==,type:str]
    pgp:
        - created_at: "2022-11-06T12:25:59Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3JvjRecrhePAQ/+IeQE6qj5oAt/5HxT78wtpcoYvh4WaWB8nblhcy9kCgLY
            0wPodyHi2uaRzwmxHA54gomnRPsPdP+OHYIeqoRIEInWQilB65z1sYcRQTMlxxKZ
            wvSTMyBPghV1bkh3/XE4w2lduAH64U/rVsQWACFJiTHiNCcbhSWCkXSYe+jc05Rl
            twBMC5rfmtDjyWfXiXvHhcdBpSkojO/LNATU7N/qGXLn+8U3uhry6jslfD4FZvab
            AdpIVlFGMP/D7jL9UKH1vtlWobDfQvWPgxV3PUYhBtsecf+hyEogfcHYMxrCRhWD
            2+XbT0w46O28aPdoI2G9TVlhMkR3QV2SI23xaDb+a9MGaeR64iv7HVLFt2wyH9p5
            Q6IdTQ9uoyax8TlbHp+8pKscbHbKYn3xiVjH9uYmj8ltXT59qAnCouNk1oEMMyVW
            TvFlk0PksABC9mpFV87WbosFgsrWEGGBH1pHs1CN7hF4jzh/0AbN1+sRFr8txLp/
            sPSL9LTaC6W8nMORKhmI0ygVNVCvxLgf+v1194YR+Iq2D5t6piCwNRl4aUyV1jup
            nrvySj8/s8bvu9FOS+6a7zFIRX/IrZI1s/SaCtT/INLDqdjyczpGGF2g9nw0NcM6
            QZw8mhL/GWBr3Z0gYpa12yZT+nERJbRlEn/JqLOBVGL1++UGKm+7n3qNSN/O5o7S
            XgHPrbDqus739T6l48+Txem7NSTDlkd3zEpMr5Qkv3qY148tfPMUdOkEDojGPj/Q
            92R5BYVKYMaACkpdzkxg/qYb90EJuSzFYzw9anM8bhWiDxn/ovuJju1PLXTe+6s=
            =Gojy
            -----END PGP MESSAGE-----
          fp: A159111F770337DC337AD38A574C7A3BA03CC798
    unencrypted_suffix: _unencrypted
    version: 3.7.3
