apiVersion: v1
data:
    database: ENC[AES256_GCM,data:I+qsXdvm1Zn3SJCD,iv:eEeW7AznTHxno2MMRXsv/Oge8MRTfqlYMfMruZWPFFA=,tag:v8HgkFREpJ/AuK7lfQIU7g==,type:str]
    user_login: ENC[AES256_GCM,data:5IaUBTkZ2lDOQu9V,iv:hbjO69f6HO6qKHvxCP3gbXZsYxiugBcXhz4fTDH39rI=,tag:ndi+cfx3tckIkF6WDvp4gw==,type:str]
    user_password: ENC[AES256_GCM,data:YvsvZ6WYQf8OnfBh8rv2tkm4LaxGZWkxTFjIgQ==,iv:H3tPDmKlcyM7hKPO5SkuGYGqEzss7G0h5TCzuzOHHnc=,tag:buywWMPYKVNjtOVsT69tVw==,type:str]
kind: Secret
metadata:
    name: guacamole
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-06T12:28:14Z"
    mac: ENC[AES256_GCM,data:Y9doyKVRoUS0tmGCM+qhzMSdEnlU9R6sPAMOFpjx1bfMcBx4ZTmnSQayX6XM4ecGjZnouy4X/zMYWbgbB6KoWOwAEzTZyD9Ejmh054TVt6iGkY+mJ0C1ewNbVel4OIdVIpZ6kOE7SJflFKOvqfBlu6n1d+4FwqRUEpOezWafX20=,iv:eK5hrFt+5WnSeN8vRh9pBXJt87v1UU516RQEW35z7JM=,tag:D9r1m/bj30r+Hq7RpEGxsA==,type:str]
    pgp:
        - created_at: "2022-11-06T12:28:14Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3JvjRecrhePAQ//Viw3NBt8/5C/wg9A4MQUUfIx0QXxD7HblloOtz/uI5ZU
            g/F7I0JlNDkH/0rQKQ5ifBVgIaSaLgtEHBtL/oAySaYZFHBGXyxJsoVAlI/RfzSX
            VDInjtbtKdwRUV6vB0EeBYefBEiKShTk3GXCPAyOnfhlJs2s/XEskO7q1L5kU+Ka
            Ryqd2KceXOMc1ha2OtzloaiVCBA0ymfq1NvrF4cBGzGjvOqydeYsvJh5OFCY+QOE
            T1fdILSe6BA1yzGKqq5aNRocHryVfTNxRfDWsYsyvU0xhuSp1iRVuas4D3sG2TFN
            XlMiUnHrrJ6eNjrFYDc1u9liIlMKvmQfriCFAj8rR6k+02ZLCsXHzx+6feHytITj
            e7w7d1ZIpBJnPkOeLEB+ms6pPMtV9Kn2kHw5+RyQXUwtSisi9YbL7vJPa/Et2dUp
            6NUk6+UG7C+5emaJICL9nVW9aHc0yTn+m7c5PeDmLR1eXX/gdukCbmlmew6XuH/d
            YZTRXvCt9rFKMIeLQAa6pjtqxvMDSr8vDjLvzsHxS5SbSQ0rTqgOwWSUwb3bP/CR
            6KrFD+8PYbFAfcQwm0fh+dAaUlLKWzxFzuA2i+W94K1+fEbHLAnARl0AUpffuJS1
            ChEc86R+DzFzbk5BEIhJogXhFb5ZwaUTW9P+zOb5CMrLPUCnY1eHQf+1io9tUEPS
            XgG1ti1d5gvmTcjTxvfaRTZ15/qRFkdLx+SBHQGZgNPWZ2qevFQPLEhwPrNA87KT
            eYh1qYk/FNObhGen6adV6GHncOTJlYt374PoxH2wzbuRHKHqd4OgIpDij9PEh0E=
            =jc7x
            -----END PGP MESSAGE-----
          fp: A159111F770337DC337AD38A574C7A3BA03CC798
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
