---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: nfs-subdir-external-provisioner
    namespace: nfs-system
spec:
    interval: 1m
    chart:
        spec:
            chart: charts/nfs-subdir-external-provisioner
            sourceRef:
                name: nfs-subdir-external-provisioner
                kind: GitRepository
            interval: 1m
    install:
        remediation:
            retries: 3
    values:
        fullnameOverride: nfs-subdir-external-provisioner
