---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: mosquitto
    namespace: mosquitto
spec:
    releaseName: mqtt
    chart:
        spec:
            chart: mosquitto
            sourceRef:
                name: k8s-at-home
                kind: HelmRepository
            version: ">=2.0.0"
    interval: 1h0m0s
    install:
        remediation:
            retries: 3
    values:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      env:
        TZ: "America/Chicago"
      persistence:
        configinc:
          enabled: true
          existingClaim: mosquitto-configinc
        data:
          enabled: true
          existingClaim: mosquitto-data
      service:
        main:
          loadBalacerIP: 10.0.21.3
          type: LoadBalancer
