---
apiVersion: v1
kind: ConfigMap
metadata:
    name: coredns
    namespace: pihole
data:
    Corefile: |
        .:5353 {
                errors
                forward . tls://1.1.1.1 tls://1.0.0.1 {
                        tls_servername cloudflare-dns.com
                        health_check 5s
                }
        }
