---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pihole
    namespace: pihole
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    storageClassName: files
