---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
    name: cert-manager
    namespace: flux-system
spec:
    dependsOn:
        - name: cert-manager-crds
          namespace: flux-system
    interval: 5m0s
    path: ./clusters/k3s.phealy.com/cert-manager
    prune: true
    sourceRef:
        kind: GitRepository
        name: flux-system
    decryption:
        provider: sops
        secretRef:
            name: sops-gpg
