---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
    name: metallb
    namespace: flux-system
spec:
    interval: 5m0s
    path: ./clusters/k3s.phealy.com/kube-vip
    prune: true
    sourceRef:
        kind: GitRepository
        name: flux-system
    decryption:
        provider: sops
        secretRef:
            name: sops-gpg
