---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: cert-manager
    namespace: cert-manager
spec:
    releaseName: cluster
    chart:
        spec:
            chart: cert-manager
            sourceRef:
                name: cert-manager
                kind: HelmRepository
            version: 1.2.0
    interval: 1h0m0s
    install:
        remediation:
            retries: 3
    values:
        fullnameOverride: cert-manager
        ingressShim:
            defaultIssuerName: letsencrypt-staging
            defaultIssuerKind: ClusterIssuer
            nodeSelector:
                beta.kubernetes.io/os: linux
        webhook:
            nodeSelector:
                beta.kubernetes.io/os: linux
        cainjector:
            nodeSelector:
                beta.kubernetes.io/os: linux
