---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: home-assistant
    namespace: home-assistant
spec:
    releaseName: cluster
    chart:
        spec:
            chart: home-assistant
            sourceRef:
                name: home-assistant
                kind: HelmRepository
            version: 8.0.0
    interval: 1h0m0s
    install:
        remediation:
            retries: 3
    values:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      env:
        TZ: "America/Chicago"
      ingress:
        enabled: false
        annotations:
          nginx.org/websocket-services: home-assistant
      persistence:
        config:
          enabled: true
          storageClass: files
          accessMode: ReadWriteOnce
          size: 1Gi
          skipuninstall: true
