---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant
resources:
    - namespace.yaml
    - repository.yaml
    - home-assistant.yaml
    - ingress-internal.yaml
    - ingress-external.yaml
    - pv.yaml
    - pvc.yaml
