---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-61df8543-5f7c-4257-ad5b-d7f51d4d3b0f
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: home-assistant
    namespace: home-assistant
  nfs:
    path: /volume1/k3s.phealy.com/home-assistant-cluster-home-assistant-config-pvc-61df8543-5f7c-4257-ad5b-d7f51d4d3b0f
    server: 10.0.23.2
  persistentVolumeReclaimPolicy: Retain
  storageClassName: files
  volumeMode: Filesystem
