---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pihole
bases:
    - ../../../apps/pihole
resources:
    - resources/pihole-dnsmasq.yaml
#    - resources/pihole-admin.yaml
patches:
    - patch: |-
        apiVersion: v1
        kind: Service
        metadata:
            name: pihole-dns-tcp
            namespace: pihole
        spec:
            loadBalancerIP: 10.0.21.2
    - patch: |-
        apiVersion: v1
        kind: Service
        metadata:
            name: pihole-dns-udp
            namespace: pihole
        spec:
            loadBalancerIP: 10.0.21.2
    - patch: |-
        - op: replace
          path: /spec/rules/0/host
          value: pihole.k3s.phealy.com
        - op: replace
          path: /spec/tls/0/hosts/0
          value: pihole.k3s.phealy.com
      target:
          group: networking.k8s.io
          version: v1
          kind: Ingress
          name: pihole
    - patch: |-
        - op: replace
          path: /spec/rules/0/host
          value: pihole-0.k3s.phealy.com
        - op: replace
          path: /spec/tls/0/hosts/0
          value: pihole-0.k3s.phealy.com
      target:
          group: networking.k8s.io
          version: v1
          kind: Ingress
          name: pihole-0
    - patch: |-
        - op: replace
          path: /spec/rules/0/host
          value: pihole-1.k3s.phealy.com
        - op: replace
          path: /spec/tls/0/hosts/0
          value: pihole-1.k3s.phealy.com
      target:
          group: networking.k8s.io
          version: v1
          kind: Ingress
          name: pihole-1
