---
apiVersion: v1
kind: ConfigMap
metadata:
    namespace: metallb-system
    name: config
data:
    config: |
        peers:
        - peer-address: 10.0.22.1
          peer-asn: 65510
          my-asn: 65509
          hold-time: 15s
        address-pools:
        - name: default
          protocol: bgp
          addresses:
          - 10.0.21.0/24
